### ISSUE TITLE
+1 to not have interactive line plot consume all gestures

### ISSUE THREAD

**Issue by stammy** [aunnnn/RHLinePlot#1]
Nice work on this! Just wanted to echo your note about wanting to work on interactive line plots not consuming all gestures. I think it would be neat to support various ways to work with it: for example, require an event to trigger horizontal scrubbing such as a long-press, or if possible only listen to horizontal movements and not vertical (in the case of scrolling a view up/down). But think the former is more than sufficient with a user-customizable long-press delay.

**Comment by aunnnn** [comment]
Hey, thanks for checking it out! I tried adding the `LongPressGesture` before the drag, but somehow the long press still consumes gestures exclusively.

So I've looked into [approaches](https://stackoverflow.com/questions/57700396/adding-a-drag-gesture-in-swiftui-to-a-view-inside-a-scrollview-blocks-the-scroll), and found like detecting horizontal drag is a good way out.

The final solution I'm going with is adding a (clear) [proxy view](https://github.com/aunnnn/RHLinePlot/blob/master/RHLinePlot/PressAndHorizontalDragGesture.swift) and let it handles the long press and horizontal pan gestures with relevant callbacks to update states. I just updated the repo, feel free to check it out.

Thanks for raising this up, somehow it motivates me to fix it!
